name: Build wheels

on: [push, pull_request]

# Default parameters for all builds
env:
  ARTIFACT_RETENTION: ${{ github.ref == 'refs/heads/master' && '30' || '7' }}

jobs:
  cpython-linux-x86_64:
    name: 'Linux CPython (${{ matrix.cibw_archs }}, ${{ matrix.manylinux_image }})'
    runs-on: ubuntu-20.04
    strategy:
      matrix:
        cibw_archs: ["x86_64"]
        manylinux_image: ["manylinux2010"]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.10'
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.1.1
        env:
          CIBW_BEFORE_BUILD: pip install cython
          CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.manylinux_image }}
          CIBW_ARCHS_LINUX: ${{ matrix.cibw_archs }}
          CIBW_BUILD: "cp38-* cp39-* cp10-*"
          CIBW_SKIP: pp*
      - uses: actions/upload-artifact@v2
        with:
          name: networkit-cp38-${{ matrix.manylinux_image}}-${{ matrix.cibw_archs }}.whl
          path: ./wheelhouse/*cp38*.whl
          retention-days: ${{ env.ARTIFACT_RETENTION }}
      - uses: actions/upload-artifact@v2
        with:
          name: networkit-cp39-${{ matrix.manylinux_image}}-${{ matrix.cibw_archs }}.whl
          path: ./wheelhouse/*cp39*.whl
          retention-days: ${{ env.ARTIFACT_RETENTION }}
      - uses: actions/upload-artifact@v2
        with:
          name: networkit-cp310-${{ matrix.manylinux_image}}-${{ matrix.cibw_archs }}.whl
          path: ./wheelhouse/*cp310*.whl
          retention-days: ${{ env.ARTIFACT_RETENTION }}

  cpython-linux-aarch64:
    name: 'Linux CPython (${{ matrix.cibw_archs }}, ${{ matrix.manylinux_image }})'
    runs-on: ${{ matrix.os }}
    strategy:
      matrix:
        os: [ubuntu-20.04]
        cibw_archs: ["aarch64"]
        manylinux_image: ["manylinux2014"]
    steps:
      - name: Set up QEMU
        uses: docker/setup-qemu-action@v1
        with:
          platforms: all
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.9'
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.1.1
        env:
          CIBW_BEFORE_BUILD: pip install cython
          CIBW_MANYLINUX_X86_64_IMAGE: ${{ matrix.manylinux_image }}
          CIBW_ARCHS_LINUX: ${{ matrix.cibw_archs }}
          CIBW_BUILD: ${{ github.ref == 'refs/heads/master' && 'cp39-* cp310-*' || 'cp310-*' }}
          CIBW_SKIP: pp*
      - uses: actions/upload-artifact@v2
        if: github.ref == 'refs/heads/master'
        with:
          name: networkit-cp39-${{ matrix.manylinux_image}}-${{ matrix.cibw_archs }}.whl
          path: ./wheelhouse/*cp39*.whl
          retention-days: ${{ env.ARTIFACT_RETENTION }}
      - uses: actions/upload-artifact@v2
        with:
          name: networkit-cp310-${{ matrix.manylinux_image}}-${{ matrix.cibw_archs }}.whl
          path: ./wheelhouse/*cp310*.whl
          retention-days: ${{ env.ARTIFACT_RETENTION }}

  cpython-macos-x86_64:
    name: 'macOS CPython  (${{ matrix.cibw_archs }})'
    runs-on: macos-latest
    strategy:
      matrix:
        cibw_archs: ["x86_64"]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.10'
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.1.1
        env:
          CIBW_BEFORE_BUILD: 
            pip install cython &&
            brew install libomp ninja
          CIBW_ARCHS_MACOS: ${{ matrix.cibw_archs }}
          CIBW_BUILD: "cp38-* cp39-* cp310-*"
          CIBW_SKIP: pp*
      - uses: actions/upload-artifact@v2
        with:
          name: networkit-cp38-macos-${{ matrix.cibw_archs }}.whl
          path: ./wheelhouse/*cp38*.whl
          retention-days: ${{ env.ARTIFACT_RETENTION }}
      - uses: actions/upload-artifact@v2
        with:
          name: networkit-cp39-macos-${{ matrix.cibw_archs }}.whl
          path: ./wheelhouse/*cp39*.whl
          retention-days: ${{ env.ARTIFACT_RETENTION }}
      - uses: actions/upload-artifact@v2
        with:
          name: networkit-cp310-macos-${{ matrix.cibw_archs }}.whl
          path: ./wheelhouse/*cp310*.whl
          retention-days: ${{ env.ARTIFACT_RETENTION }}

  cpython-macos-arm64:
    name: 'macOS CPython  (${{ matrix.cibw_archs }})'
    runs-on: macos-latest
    strategy:
      matrix:
        cibw_archs: ["arm64"]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.10'
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.1.1
        env:
          CIBW_BEFORE_BUILD: 
            pip install cython &&
            brew install libomp ninja &&
            pip install --pre -i https://pypi.anaconda.org/scipy-wheels-nightly/simple scipy
          CIBW_ENVIRONMENT: CXX=c++ NETWORKIT_OSX_CROSSBUILD=ON
          CIBW_ARCHS_MACOS: ${{ matrix.cibw_archs }}
          CIBW_BUILD: "cp39-* cp310-*"
          CIBW_SKIP: pp*
      - uses: actions/upload-artifact@v2
        with:
          name: networkit-cp39-macos-${{ matrix.cibw_archs }}.whl
          path: ./wheelhouse/*cp39*.whl
          retention-days: ${{ env.ARTIFACT_RETENTION }}
      - uses: actions/upload-artifact@v2
        with:
          name: networkit-cp310-macos-${{ matrix.cibw_archs }}.whl
          path: ./wheelhouse/*cp310*.whl
          retention-days: ${{ env.ARTIFACT_RETENTION }}

  cpython-windows:
    name: 'Windows CPython (${{ matrix.cibw_archs }})'
    runs-on: windows-latest
    strategy:
      matrix:
        cibw_archs: [amd64]
    steps:
      - uses: actions/checkout@v2
        with:
          submodules: true
      - name: Setup devCmd (vstools)
        uses: ilammy/msvc-dev-cmd@v1
      - uses: actions/setup-python@v2
        name: Install Python
        with:
          python-version: '3.10'
      - name: Build wheels
        uses: pypa/cibuildwheel@v2.1.2
        env:
          CIBW_BEFORE_BUILD: pip install cython ipython
          CIBW_ARCHS: "AMD64"
          CIBW_BUILD: "cp38-* cp39-* cp310-*"
          CIBW_SKIP: pp*
      - uses: actions/upload-artifact@v2
        with:
          name: networkit-cp38-win-${{ matrix.cibw_archs }}.whl
          path: ./wheelhouse/*cp38*.whl
          retention-days: ${{ env.ARTIFACT_RETENTION }}
      - uses: actions/upload-artifact@v2
        with:
          name: networkit-cp39-win-${{ matrix.cibw_archs }}.whl
          path: ./wheelhouse/*cp39*.whl
          retention-days: ${{ env.ARTIFACT_RETENTION }}
      - uses: actions/upload-artifact@v2
        with:
          name: networkit-cp310-win-${{ matrix.cibw_archs }}.whl
          path: ./wheelhouse/*cp310*.whl
          retention-days: ${{ env.ARTIFACT_RETENTION }}
